name: genotox
channels:
  - default
  - rdkit
  - conda-forge 
  - chembl
dependencies:
  - pip
  - python=3.6
  - setuptools=>38.4.0
  - scikit-learn=0.24.1
  - imbalanced-learn=>0.8.0
  - requests
  - rdkit=2020.09.1.0
  - pandas
  - psycopg2
  - chembl_structure_pipeline
  - python-docx
  - openpyxl
  - appdirs
  - pip:
     - django